### ISSUE TITLE
Running the setup.py script on a clean clone doesn't work

### ISSUE THREAD

**Issue by coffeelover82** [turner11/Traffic#11]
(Traffic-SOME_HASH) X:\Path\Traffic>python settings\setup.py
Traceback (most recent call last):
  File "settings\setup.py", line 5, in <module>
    from common.utils import init_log
ModuleNotFoundError: No module named 'common'

(Traffic-SOME_HASH) X:\Path\Traffic\settings>python setup.py
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from common.utils import init_log
ModuleNotFoundError: No module named 'common'

**Comment by turner11** [comment]
Run it using:
```
python __main__ -s
```
